---
openapi: 3.0.1
info:
  title: AMHS API
  description: Test API for AMHS
  version: 1.0.0
paths:
  /leads:
    get:
      description: Get all Leads
      responses:
        200:
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Lead'
              examples:
                Lead example:
                  value: |-
                    {
                        "id": 1,
                        "first_name": "John"
                        "middle_name": "M"
                        "last_name": "Doe"
                        "status": "opportunity"
                    }
    post:
      description: Create new Lead
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Lead'
        required: true
      responses:
        201:
          content:
            application/json:
              schema:
                type: string
              examples:
                Created:
                  value: '"Created"'
components:
  schemas:
    404:
      title: Root Type for 404
      description: The root of the 404 type's schema.
      type: object
      properties:
        code:
          format: int32
          description: HTTP Status Code
          type: integer
        message:
          description: Error message
          type: string
    Lead:
      title: Root Type for Lead
      description: The root of the Lead type's schema.
      type: object
      properties:
        id:
          format: int32
          type: integer
        first_name:
          type: string
        middle_name:
          type: string
        last_name:
          type: string
        status:
          type: string
